apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: develop--service-foo
  namespace: argocd
spec:
  destination:
    namespace: develop
    server: https://kubernetes.default.svc
  project: default
  source:
    path: develop/service-foo
    repoURL: https://github.com/yuya-takeyama/gitops-repo
    targetRevision: master
