apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production--service-foo
  namespace: argocd
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: default
  source:
    path: production/service-foo
    repoURL: https://github.com/yuya-takeyama/gitops-repo
    targetRevision: master
  syncPolicy:
    automated: {}
